server:
  port: 9201
service-url:
  user-service: http://localhost:7201
spring:
  cloud:
    gateway:
      routes:
        - id: remoteaddr_route
          uri: ${service-url.user-service}
          predicates:
            - RemoteAddr=192.168.0.108/24